---
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

logging:
  level:
    com:
      netflix:
        discovery: "off"
        eureka:
          registry: "off"
