---
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    com:
      netflix:
        discovery: "off"
        eureka:
          registry: "off"

server:
  shutdown: graceful
