---
spring:
  graphql:
    path: /fb-data-viewer/graphql
    graphiql:
      enabled: true
      path: /fb-data-viewer/graphiql
logging:
  level:
    org:
      springframework:
        graphql: INFO
        jdbc:
          core: INFO
