---
spring:
  graphql:
    path: /fbraw-viewer-api/graphql
    graphiql:
      enabled: true
      path: /fbraw-viewer-api/graphiql
logging:
  level:
    org:
      springframework:
        graphql: DEBUG
        jdbc:
          core: INFO

