---
spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

document:
  resolver:
    timeout: 30000
    maxRetries: 4
    retryWaitTime: 2000
    readDelay: 2000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
